[package]
name = "b_toolkit"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
comrak = "0.29.0"
wasm-bindgen = "0.2.95"
base64 = "0.22.1"
serde_json = "1.0.132"
web-sys = "0.3.72"
wasm-bindgen-futures = "0.4.45"